apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-public-ingress-reader
  namespace: public-sites
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-public-ingress-reader
  namespace: public-sites
  labels:
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-public-ingress-reader
subjects:
  - kind: ServiceAccount
    name: traefik-public
    namespace: {{ .Release.Namespace }}
