apiVersion: v1
kind: ConfigMap
metadata:
  name: application-registry-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: application-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
data:
  config.yml: |-
    version: 0.1
    log:
      level: info
      fields:
        service: application-registry
    storage:
      delete:
        enabled: true
      filesystem:
        rootdirectory: /var/lib/registry
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
    http:
      addr: 0.0.0.0:5000
      draintimeout: 60s
      headers:
        Docker-Distribution-API-Version: [registry/2.0]
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: {{ .Values.auth.realm | quote }}
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
