apiVersion: v1
kind: Service
metadata:
  name: application-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: application-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: application-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP

