{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "grafana-pvc",
    "namespace": "monitoring",
    "annotations": {
      "helm.sh/resource-policy": "keep"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "5Gi"
      }
    },
    "storageClassName": "longhorn"
  }
}
