---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCLpPYBcFqI9T5X2iAanb+2tcbjVcp7lkVZcH1pVcAojqz2sBVIr3o+o67r1W7VpUwE5400ZqUaMbaXI10T7DPM03c7LSPBXViS1YBLxNQr4if2Vm6TO43irNDWYz6dmuFf9Un9FT0IlFYEpcEFhu2ghTqJxqV1AlUvkJ+/2JFcd24qrU0d2vwt+C93pArdJWiZwMBe5PTxr/fteDCA/BtAWj95jpzAEJ0FlgM2PKDJoVKXmg1ZggB3tYIVtxMrwchad0wRVwt1smB97fs9LRjjUlU5Ue0i665eqDONe0wDbUNHFcvg0KYuoBV49LBiS1XxZHM4LmlOpLDknd1CxtDEuWhmjwtAaC11fEaMQTWnHnNaISLLFdwTEzynM6QVVdnfVXm713vLcsAZ2188k+LqBt4BwNvJ5rr4Ji3L3FXrCtm7CgJFEFdSZTsJNAUviqmmrnoKijaKJfmdLl5zfrxTCbUwarjt4Wrk5tz4LJV0szLaiEra/BEcH7+IrGZltFHd+F0rsK0O00XQCVq0sCpgae3BPCgTdHqm4oN8JftiJpebx1YQGPwXHy8zz1vcDQnc5sUq7IOrJll7WS7LMnTx98RYznnevFyir2meDjynZbUVh+3iI3aqLSYx08dR4yD8MgzC1i6oNAboHZ7JNyuTa4KyaZiuCAZ/C9Cer4vxLAHjvgJRAK7l1ayFQ1GcfkYVVPzUDwWLuyr4PA7NP++LJjqPHgHM5SkHPZJwXZt+by1KRmIEUQXk
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
