---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    password: AgBzm0U1/3kITEQZltOwMXncN7aCEnm59KgytFuA0E1kkQc9MPJfn1yq6dQwkNoZjoeZW6HQ7TF7Cx19Jsh2QcRI6bkv4t6JigZFNDDlfPfd+bw+jpszoL/NNwBhryQaHydeWzb6f9qvpFDUYQvgxRwkb7QvQ8asthSqM3HdFrjcutx2cOPq2fjdxForVoW6HAjggULB3gZEDBmnHJxhrxl+bTnJNuOh08OMepoMMWi3wwwy58TTLZpowNtt1PovrllVgbS0smBsmGg1BTPV3Uk0JSJL7Qumx+4q8WwqmP6KslJ2hbgBze/u3EfVDJkXCTd2Oz9aeD+UatTd7/Dkb4+jApZ7OJ0U2EE5Wr3A5QZOBnwEzv4qgSshzkcVMNPV0xJPVWn9AVHBAJ9QMxF75XTXS1IAOCc6mlmp/b9iwZGlf+aIRK9eRtetv9p4/FQxtsRTIft1XDTlhKCC3lY27N4smcl3WwMrHChNPGY1CBHtEtl70QDBWbSDUJKj1kesCNrNvw5IKpxW+tenk5BAo3VJn4PKAFygJXaQ1S2LKh1toPJgL9JTnYJAUUTPlG7BC6NuvVZskP1ZxF3Rswgk+soGx/BzXz4eSiUSVDcAHJZLLtM5BB6txAdSWKtnzPyVyd8Yvd35dmxLZjtfGfmAazyr826PWm+RgArdyWfqa6yQaq8SqyLOhOVVuhj/l2NcNd1qD+YbJbJuxJ2J5Q3xywSeMHzBiX6Q4O3YVGfhTKtBCzyTMZd3gVY1xntOFrtVccc=
  template:
    metadata:
      name: pihole-password
      namespace: pihole
    type: Opaque
