apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-public-applications
  namespace: public-sites
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-public-applications-token
  namespace: public-sites
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/service-account.name: argocd-public-applications
type: kubernetes.io/service-account-token
