apiVersion: v2
name: homelab-traefik-public
description: Isolated ingress controller for Cloudflare Tunnel public applications
type: application
version: 0.2.0
appVersion: "3.7.10"
dependencies:
  - name: traefik
    version: 41.2.0
    repository: https://traefik.github.io/charts
